local cl = {}
local gghk = gameplay.get_hash_key
cl.parent = menu.add_feature("Custom Loadout", "parent", 0).id
cl.saveddir = utils.get_appdata_path("PopstarDevs\\2Take1Menu\\scripts\\loadout_data\\", "")
cl.attachments_table = {
    [gghk("COMPONENT_PISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_PISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_PI_FLSH")] = "Flashlight",
    [gghk("COMPONENT_AT_PI_SUPP_02")] = "Suppressor",
    [gghk("COMPONENT_PISTOL_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_COMBATPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMBATPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_PI_SUPP")] = "Suppressor",
    [gghk("COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_APPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_APPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_APPISTOL_VARMOD_LUXE")] = "Gilded Gun Metal Finish",
    [gghk("COMPONENT_PISTOL50_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_PISTOL50_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_AR_SUPP_02")] = "Suppressor",
    [gghk("COMPONENT_PISTOL50_VARMOD_LUXE")] = "Platinum Pearl Deluxe Finish",
    [gghk("COMPONENT_MICROSMG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MICROSMG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_SCOPE_MACRO")] = "Scope",
    [gghk("COMPONENT_MICROSMG_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_SMG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SMG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SMG_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_AT_AR_FLSH")] = "Flashlight",
    [gghk("COMPONENT_AT_SCOPE_MACRO_02")] = "Scope",
    [gghk("COMPONENT_SMG_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_ASSAULTSMG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_ASSAULTSMG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_ASSAULTRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_ASSAULTRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_ASSAULTRIFLE_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_AT_AR_AFGRIP")] = "Grip",
    [gghk("COMPONENT_ASSAULTRIFLE_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_CARBINERIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_CARBINERIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_CARBINERIFLE_CLIP_03")] = "Box Magazine",
    [gghk("COMPONENT_AT_SCOPE_MEDIUM")] = "Scope",
    [gghk("COMPONENT_AT_AR_SUPP")] = "Suppressor",
    [gghk("COMPONENT_CARBINERIFLE_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_ADVANCEDRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_ADVANCEDRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_SCOPE_SMALL")] = "Scope",
    [gghk("COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE")] = "Gilded Gun Metal Finish",
    [gghk("COMPONENT_MG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_SCOPE_SMALL_02")] = "Scope",
    [gghk("COMPONENT_MG_VARMOD_LOWRIDER")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_COMBATMG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMBATMG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_COMBATMG_VARMOD_LOWRIDER")] = "Etched Gun Metal Finish",
    [gghk("COMPONENT_AT_SR_SUPP")] = "Suppressor",
    [gghk("COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE")] = "Gilded Gun Metal Finish",
    [gghk("COMPONENT_ASSAULTSHOTGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_ASSAULTSHOTGUN_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SNIPERRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_AT_SCOPE_LARGE")] = "Zoom Scope",
    [gghk("COMPONENT_AT_SCOPE_MAX")] = "Advanced Scope",
    [gghk("COMPONENT_SNIPERRIFLE_VARMOD_LUXE")] = "Etched Wood Grip Finish",
    [gghk("COMPONENT_HEAVYSNIPER_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SNSPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SNSPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SNSPISTOL_VARMOD_LOWRIDER")] = "Etched Wood Grip Finish",
    [gghk("COMPONENT_BULLPUPRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_BULLPUPRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_BULLPUPRIFLE_VARMOD_LOW")] = "Gilded Gun Metal Finish",
    [gghk("COMPONENT_SPECIALCARBINE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SPECIALCARBINE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SPECIALCARBINE_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER")] = "Etched Gun Metal Finis",
    [gghk("COMPONENT_HEAVYPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_HEAVYPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_HEAVYPISTOL_VARMOD_LUXE")] = "Etched Wood Grip Finish",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_AT_SIGHTS")] = "Holographic Sight",
    [gghk("COMPONENT_AT_SCOPE_MACRO_MK2")] = "Small Scope",
    [gghk("COMPONENT_AT_SCOPE_MEDIUM_MK2")] = "Large Scope",
    [gghk("COMPONENT_AT_MUZZLE_01")] = "Flat Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_02")] = "Tactical Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_03")] = "Fat-End Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_04")] = "Precision Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_05")] = "Heavy Duty Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_06")] = "Slanted Muzzle Brake",
    [gghk("COMPONENT_AT_MUZZLE_07")] = "Split-End Muzzle Brake",
    [gghk("COMPONENT_AT_AR_AFGRIP_02")] = "Grip",
    [gghk("COMPONENT_AT_SC_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_SC_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_AT_SCOPE_MACRO_02_MK2")] = "Medium Scope",
    [gghk("COMPONENT_AT_SCOPE_SMALL_MK2")] = "Medium Scope",
    [gghk("COMPONENT_AT_BP_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_BP_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CLIP_01")] = "Default Shells",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING")] = "Steel Buckshot Shells",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE")] = "Explosive Slugs",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT")] = "Flechette Shells",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY")] = "Dragon's Breath Shells",
    [gghk("COMPONENT_AT_SR_SUPP_03")] = "Suppressor",
    [gghk("COMPONENT_AT_MUZZLE_08")] = "Squared Muzzle Brake",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT")] = "Hollow Point Rounds",
    [gghk("COMPONENT_SNSPISTOL_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_AT_PI_FLSH_03")] = "Flashlight",
    [gghk("COMPONENT_AT_PI_RAIL_02")] = "Mounted Scope",
    [gghk("COMPONENT_AT_PI_COMP_02")] = "Compensator",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE")] = "Brushstroke Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE")] = "Woodland Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE")] = "Skull",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE")] = "Sessanta Nove",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE")] = "Perseus",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE")] = "Leopard",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE")] = "Zebra",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE")] = "Geometric",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE")] = "Boom!",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE")] = "Patriotic",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_SNSPISTOL_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2")] = "Zoom Scope",
    [gghk("COMPONENT_AT_MRFL_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_MRFL_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_DOUBLEACTION_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_RAYPISTOL_VARMOD_XMAS18")] = "Festive tint",
    [gghk("COMPONENT_REVOLVER_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_REVOLVER_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT")] = "Hollow Point Rounds",
    [gghk("COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_REVOLVER_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_PI_COMP_03")] = "Compensator",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_REVOLVER_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_GUSENBERG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_GUSENBERG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_VINTAGEPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_VINTAGEPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_RAILGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MARKSMANRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MARKSMANRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM")] = "Zoom Scope",
    [gghk("COMPONENT_MARKSMANRIFLE_VARMOD_LUXE")] = "Yusuf Amir Luxury Finish",
    [gghk("COMPONENT_HEAVYSHOTGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_HEAVYSHOTGUN_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_HEAVYSHOTGUN_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_CERAMICPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_CERAMICPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_CERAMICPISTOL_SUPP")] = "Suppressor",
    [gghk("COMPONENT_COMBATSHOTGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_GADGETPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MILITARYRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MILITARYRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_MILITARYRIFLE_SIGHT_01")] = "Iron Sights",
    [gghk("COMPONENT_NAVYREVOLVER_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_KNUCKLE_VARMOD_BASE")] = "Base Model",
    [gghk("COMPONENT_KNUCKLE_VARMOD_PIMP")] = "The Pimp",
    [gghk("COMPONENT_KNUCKLE_VARMOD_BALLAS")] = "The Ballas",
    [gghk("COMPONENT_KNUCKLE_VARMOD_DOLLAR")] = "The Hustler",
    [gghk("COMPONENT_KNUCKLE_VARMOD_DIAMOND")] = "The Rock",
    [gghk("COMPONENT_KNUCKLE_VARMOD_HATE")] = "The Hater",
    [gghk("COMPONENT_KNUCKLE_VARMOD_LOVE")] = "The Lover",
    [gghk("COMPONENT_KNUCKLE_VARMOD_PLAYER")] = "The Player",
    [gghk("COMPONENT_KNUCKLE_VARMOD_KING")] = "The King",
    [gghk("COMPONENT_KNUCKLE_VARMOD_VAGOS")] = "The Vagos",
    [gghk("COMPONENT_MARKSMANPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMBATPDW_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMBATPDW_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_COMBATPDW_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_DBSHOTGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMPACTRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMPACTRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_COMPACTRIFLE_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_MACHINEPISTOL_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MACHINEPISTOL_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_MACHINEPISTOL_CLIP_03")] = "Drum Magazine",
    [gghk("COMPONENT_REVOLVER_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_REVOLVER_VARMOD_BOSS")] = "VIP Variant",
    [gghk("COMPONENT_REVOLVER_VARMOD_GOON")] = "Bodyguard Variant",
    [gghk("COMPONENT_SWITCHBLADE_VARMOD_BASE")] = "Default Handle",
    [gghk("COMPONENT_SWITCHBLADE_VARMOD_VAR1")] = "VIP Variant",
    [gghk("COMPONENT_SWITCHBLADE_VARMOD_VAR2")] = "Bodyguard Variant",
    [gghk("COMPONENT_AUTOSHOTGUN_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMPACTLAUNCHER_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MINISMG_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_MINISMG_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT")] = "Hollow Point Rounds",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_PISTOL_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_PI_RAIL")] = "Mounted Scope",
    [gghk("COMPONENT_AT_PI_FLSH_02")] = "Flashlight",
    [gghk("COMPONENT_AT_PI_COMP")] = "Compensator",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_02_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_03_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_04_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_05_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_06_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_07_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_08_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_09_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_10_SLIDE")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE")] = "Patriotic",
    [gghk("COMPONENT_PISTOL_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_PISTOL_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_AR_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_AR_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_CR_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_CR_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_COMBATMG_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_MG_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_MG_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_COMBATMG_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_SMG_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_SMG_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_SMG_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT")] = "Hollow Point Rounds",
    [gghk("COMPONENT_SMG_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_SMG_MK2_CLIP_TRACER")] = "Tracer Rounds",
    [gghk("COMPONENT_AT_SIGHTS_SMG")] = "Holographic Sight",
    [gghk("COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2")] = "Medium Scope",
    [gghk("COMPONENT_AT_SCOPE_SMALL_SMG_MK2")] = "Medium Scope",
    [gghk("COMPONENT_AT_SB_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_SB_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_SMG_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_SMG_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_SMG_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_SMG_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_SMG_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_SMG_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_SMG_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_SMG_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_SMG_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_SMG_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_SMG_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING")] = "Armor Piercing Rounds",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE")] = "Explosive Rounds",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ")] = "Full Metal Jacket Rounds",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY")] = "Incendiary Rounds",
    [gghk("COMPONENT_AT_SCOPE_LARGE_MK2")] = "Zoom Scope",
    [gghk("COMPONENT_AT_SCOPE_NV")] = "Night Vision Scope",
    [gghk("COMPONENT_AT_SCOPE_THERMAL")] = "Thermal Scope",
    [gghk("COMPONENT_AT_MUZZLE_09")] = "Bell-End Muzzle Brake	",
    [gghk("COMPONENT_AT_SR_BARREL_01")] = "Default Barrel",
    [gghk("COMPONENT_AT_SR_BARREL_02")] = "Heavy Barrel",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO")] = "Digital Camo",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_02")] = "Brushstroke Camo",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_03")] = "Woodland Camo",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_04")] = "Skull",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_05")] = "Sessanta Nove",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_06")] = "Perseus",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_07")] = "Leopard",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_08")] = "Zebra",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_09")] = "Geometric",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_10")] = "Boom!",
    [gghk("COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01")] = "Patriotic",
    [gghk("COMPONENT_HEAVYRIFLE_CLIP_01")] = "Default Clip",
    [gghk("COMPONENT_HEAVYRIFLE_CLIP_02")] = "Extended Clip",
    [gghk("COMPONENT_HEAVYRIFLE_SIGHT_01")] = "Iron Sights",
    [gghk("COMPONENT_HEAVYRIFLE_CAMO1")] = "Digital Camo",
}
cl.weapons_table = {
    MELEE = {
        Antique_Cavalry_Dagger = 2460120199,
        Baseball_Bat = 2508868239,
        Bottle = 4192643659,
        Crowbar = 2227010557,
        Fists = 2725352035,
        Flashlight = 2343591895,
        Golf_Club = 1141786504,
        Hammer = 1317494643,
        Hatchet = 4191993645,
        Knuckle_Duster = 3638508604,
        Knife = 2578778090,
        Machete = 3713923289,
        Switchblade = 3756226112,
        Nightstick = 1737195953,
        Pipe_Wrench = 419712736,
        Battle_Axe = 3441901897,
        Pool_Cue = 2484171525,
        Stone_Hatchet = 940833800
    },
    HANDGUNS = {
        Pistol = 453432689,
        Pistol_MK_II = 3219281620,
        Combat_Pistol = 1593441988,
        AP_Pistol = 584646201,
        Stun_Gun_MP = 911657153,
        Stun_Gun_SP = 1171102963,
        Pistol_50 = 2578377531,
        SNS_Pistol = 3218215474,
        SNS_Pistol_MK_II = 2285322324,
        Heavy_Pistol = 3523564046,
        Vintage_Pistol = 0x83839C4,
        Flare_Gun = 1198879012,
        Marksman_Pistol = 3696079510,
        Revolver = 3249783761,
        Revolver_MK_II = 3415619887,
        Double_Action_Revolver = 2548703416,
        Ceramic_Pistol = 727643628,
        Navy_Revolver = 2441047180,
        Perico_Pistol = 1470379660,
        Up_n_Atomizer = 2939590305
    },
    SMG = {
        Micro_SMG = 324215364,
        SMG = 736523883,
        SMG_MK_II = 2024373456,
        Assault_SMG = 4024951519,
        Combat_PDW = 171789620,
        Machine_Pistol = 3675956304,
        Mini_SMG = 3173288789,
        Unholy_Hellbringer = 1198256469
    },
    SHOTGUNS = {
        Combat_Shotgun = 94989220,
        Sweeper_Shotgun = 317205821,
        Pump_Shotgun = 487013001,
        Heavy_Shotgun = 984333226,
        Pump_Shotgun_MK_II = 1432025498,
        Sawed_Off_Shotgun = 2017895192,
        Bullpup_Shotgun = 2640438543,
        Musket = 2828843422,
        Assault_Shotgun = 3800352039,
        Double_Barrel_Shotgun = 4019527611
    },
    ASSAULT_RIFLES = {
        Assault_Rifle = 3220176749,
        Assault_Rifle_MK_II = 961495388,
        Carbine_Rifle = 2210333304,
        Carbine_Rifle_MK_II = 4208062921,
        Advanced_Rifle = 2937143193,
        Special_Carbine = 3231910285,
        Special_Carbine_MK_II = 2526821735,
        Bullpup_Rifle = 2132975508,
        Bullpup_Rifle_MK_II = 2228681469,
        Compact_Rifle = 1649403952,
        Military_Rifle = 2636060646,
        Heavy_Rifle = 3347935668
    },
    MACHINE_GUNS = {
        MG = 2634544996,
        Combat_MG = 2144741730,
        Combat_MG_MK_II = 3686625920,
        Gusenberg_Sweeper = 1627465347
    },
    SNIPER_RIFLES = {
        Sniper_Rifle = 100416529,
        Heavy_Sniper = 205991906,
        Heavy_Sniper_MK_II = 177293209,
        Marksman_Rifle = 3342088282,
        Marksman_Rifle_MK_II = 1785463520
    },
    HEAVY_WEAPONS = {
        RPG = 2982836145, -- or 1752584910 ???? dafuq
        Grenade_Launcher = 2726580491,
        --grenadelauncher_smoke = 0x4DD2DC56,
        Minigun = 1119849093,
        Firework_Launcher = 2138347493,
        Railgun = 1834241177,
        Homing_Launcher = 1672152130,
        Compact_Grenade_Launcher = 125959754,
        Widowmaker = 3056410471,
        Compact_EMP_LAUNCHER = 3676729658
    },
    THROWABLES = {
        Grenade = 2481070269,
        BZ_Gas = 2694266206,
        Tear_Gas = 4256991824, -- smokegrenade 0xFDBC8A50 = Tear Gas 4256991824? seems like it
        Flare = 1233104067,
        Molotov = 615608432,
        Sticky_Bomb = 741814745,
        Proximity_Mine = 2874559379,
        Snowball = 126349499,
        Pipe_Bomb = 3125143736,
        Ball = 600439132
    },
    MISC = {
        Fire_Extinguisher = 101631238,
        --parachute = 0xFBAB5776,
        Fertilizer_Can = 406929569,
        Jerry_Can = 883325847,
        Hazardous_Jerry_Can = 3126027122
    }
}

menu.add_feature("Save Loadout", "action", cl.parent, function()
    local charS,charE = "   ","\n"
    cl.pped = player.get_player_ped(player.player_id())
    cl.file = io.open(cl.saveddir .. "\\loadout.lua", "wb")
    cl.file:write("return {" .. charE)
    for category, wweapon in pairs(cl.weapons_table) do
        for n, weapon_hash in pairs(wweapon) do
            if weapon.has_ped_got_weapon(cl.pped, weapon_hash) then
                cl.file:write(charS .. "[" .. weapon_hash .. "] = ")
                local num_attachments = 0
                for attachment_hash, attachment_name in pairs(cl.attachments_table) do
                    if (native.call(0x5CEE3DF569CECAB0, weapon_hash, attachment_hash)) then
                        if weapon.has_ped_got_weapon_component(cl.pped, weapon_hash, attachment_hash) then
                            num_attachments = num_attachments + 1
                            if num_attachments == 1 then
                                cl.file:write("{")
                            else
                                cl.file:write(",")
                            end
                            cl.file:write(charE .. charS .. charS .. "[" .. num_attachments .. "] = " .. attachment_hash)
                        end
                    end
                end
                local cur_tint = weapon.get_ped_weapon_tint_index(cl.pped, weapon_hash)
                if num_attachments > 0 then
                    cl.file:write("," .. charE .. charS .. charS .. "[\"tint\"] = " .. cur_tint)
                    cl.file:write(charE .. charS .. "}," .. charE)
                else
                    cl.file:write("{" .. charE .. charS .. charS .. "[\"tint\"] = " .. cur_tint)
                    cl.file:write(charE .. charS .. "}," .. charE)
                end
            end
        end
    end
    cl.file:write("}")
    cl.file:close()
    menu.notify("Loudout saved")
end)

cl.load_loadout = menu.add_feature("Load Loadout", "action", cl.parent, function()
    if utils.file_exists(cl.saveddir.."\\loadout.lua") then
        system.yield()
        cl.pped = player.get_player_ped(player.player_id())
        weapon.remove_all_ped_weapons(cl.pped)
        loadout_table = dofile(cl.saveddir .. "\\loadout.lua")
        system.yield()
        for w_hash, attach in pairs(loadout_table) do
            weapon.give_delayed_weapon_to_ped(cl.pped, w_hash, 10, false)
            for n, a_hash in pairs(attach) do
                if n ~= "tint" then
                    weapon.give_weapon_component_to_ped(cl.pped, w_hash, a_hash)
                    system.yield(10)
                end
            end
            weapon.set_ped_weapon_tint_index(cl.pped, w_hash, attach["tint"])
        end
        menu.notify("Loadout equipped")
    else
        menu.notify("Loadout not found")
    end
end)

local original = system.yield -- fix by kektram
system.yield = function(ms)
    ms = ms and ms >= 0 and ms or 0
    local time = utils.time_ms() + ms
    repeat
        original(0)
    until utils.time_ms() > time
end

local sggi = script.get_global_i
local sw = system.yield
cl.autoload = menu.add_feature("Auto Load", "toggle", cl.parent, function(f)
    while f.on do
        sw()
        if sggi(1574991) ~= 66 then
            repeat
                sw()
            until sggi(1574991) == 66
            sw(1000)
            cl.load_loadout:toggle()
        end
    end
end)
cl.autoload.on = true
